<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV8Bi0QO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV8Bi0QO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerV8Bi0QO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerV8Bi0QO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerV8Bi0QO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'V8Bi0QO',
    'container.build_id' => 'c9487b1f',
    'container.build_time' => 1613344527,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV8Bi0QO');
