<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTVEwOxp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTVEwOxp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTVEwOxp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTVEwOxp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTVEwOxp\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TVEwOxp',
    'container.build_id' => 'e1e2f922',
    'container.build_time' => 1613572144,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTVEwOxp');
